### ISSUE TITLE
Zbarcam for Python 3

### ISSUE THREAD

**Issue by 11USERNAME11** [kivy-garden/garden.zbarcam#13]
I can't use it for python 3(because of zbar). I found some libraries for decoding qr code for third version of language which don't use zbar. But I can't create right recipes for buildozer. May be you can help me? And we will add Python 3 support

**Comment by AndreMiras** [comment]
Thank you for the report. I thought I already created a ticket for it with the link to the upstream bug, but apparently not.
Upstream issue https://sourceforge.net/p/zbar/bugs/86/

Regarding the buildozer recipes, please share what you've tried so far and your errors and we can try to have a look together.

**Comment by 11USERNAME11** [comment]
So, I found a many(real many) libraries which support zbar for Python 3. And I was trying to build apk with it. Some libs crashed with buildozer(need custom recipe). Some libs crashed by openin app("libzbar.so.0" not found"). Now I'm trying to create a compiled recipe to zbarlight. And I can't understand which code must be in there. I read a zbar recipe but didn't understand how it works. I home that you can help me with creating a recipe

**Comment by 11USERNAME11** [comment]
There are all libs that I found: zbar_py, zbar-ctypes,libzbar-ctypes,libzbar-cffi,zbarlight, pyzbar. May be you will understand how customize recipe to build apk with it

**Comment by 11USERNAME11** [comment]
I wrote simple recipe and now have this error:
 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.5/src/zbarlight/_zbarlight.o -lzbar -o build/lib.linux-i686-3.5/zbarlight/_zbarlight.cpython-35m-i386-linux-gnu.so
i686-linux-gnu-gcc: error: unrecognized command line option '-mfloat-abi=softfp'
i686-linux-gnu-gcc: error: unrecognized command line option '-mfpu=vfp'
i686-linux-gnu-gcc: error: unrecognized command line option '-mthumb'
error: command 'i686-linux-gnu-gcc' failed with exit status 1

**Comment by AndreMiras** [comment]
I may take a look at it soon, but I believe we need to have https://github.com/kivy-garden/garden.zbarcam/issues/14 right before.

**Comment by AndreMiras** [comment]
Since #14 is done I've started the migration. I've picked up TODO rather than https://github.com/zplab/zbar-py because the former seemed more in active development and had more stars. However it already has an annoying feature that I've reported here https://github.com/Polyconseil/zbarlight/issues/23
It seems to work on Linux, now I'm working on the Android recipe.

**Comment by AndreMiras** [comment]
@11USERNAME11 there's apparently a working Pillow recipe here https://github.com/kivy/python-for-android/pull/786#issuecomment-414744092 if you want to give it a try

**Comment by 11USERNAME11** [comment]
So, I understood that you're trying to use zbarpy for Python3, aren't you? If I'm right we need to use NumPy for this lib. But NumPy can't work with buildozer and third version of Python

**Comment by AndreMiras** [comment]
No I'm planning to use `zbarlight`.
Regarding `numpy` under Python3 I think it runs just fine since https://github.com/kivy/python-for-android/pull/1343
If you had an issue with it, please report it upstream

**Comment by gbm001** [comment]
I have got this working on Python 3 (eventually):
https://github.com/kivy/kivy/issues/5939#issuecomment-431180980

Change:
`buf = '\x00' * self._bufsize`
to
`buf = b'\x00' * self._bufsize`
in core/camera/camera_android.py (somewhere around line 129).

**Comment by AndreMiras** [comment]
Sweet well done! :clap: 
Feel free to submit PR. If not I can take make the change later.

**Comment by gbm001** [comment]
I forgot to mention the change was in Kivy, not in zbarlight. I've posted in their issues tracker for what looks like the same issue:
https://github.com/kivy/kivy/issues/5939
but I haven't done proper testing (e.g. in Python 2/3) and I've only just started playing with Kivy/P4A...

**Comment by AndreMiras** [comment]
Yep sure, you can still give it a try to pull request it upstream. Or until then eventually add a local recipe patch

**Comment by AndreMPCosta** [comment]
> I have got this working on Python 3 on android (eventually):
> [kivy/kivy#5939 (comment)](https://github.com/kivy/kivy/issues/5939#issuecomment-431180980)
> 
> Change:
> `buf = '\x00' * self._bufsize`
> to
> `buf = b'\x00' * self._bufsize`
> in core/camera/camera_android.py (somewhere around line 129). I also had to change the ('TODO hardcoded') paths in the recipe for zbarlight (-lpython3.6m instead of -lpython2.7).
> 
> `requirements = hostpython3crystax==3.6,python3crystax==3.6,kivy,Pillow,libiconv,libzbar,zbarlight==1.2`
> `osx.kivy_version = 1.11.0dev` (originally at least, with the patch above)
> and the latest p4a.

How do you have it working with those requirements?

For instance:

Could not find a version that satisfies the requirement libzbar (from versions: )
No matching distribution found for libzbar
